// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) 

package org.apache.commons.httpclient;


// Referenced classes of package org.apache.commons.httpclient:
//            NameValuePair, HeaderElement, HttpException

public class Header extends NameValuePair
{

    public Header()
    {
        this(null, null);
    }

    public Header(String s, String s1)
    {
        super(s, s1);
        isAutogenerated = false;
    }

    public Header(String s, String s1, boolean flag)
    {
        super(s, s1);
        isAutogenerated = false;
        isAutogenerated = flag;
    }

    public HeaderElement[] getElements()
    {
        return HeaderElement.parseElements(getValue());
    }

    public HeaderElement[] getValues()
        throws HttpException
    {
        return HeaderElement.parse(getValue());
    }

    public boolean isAutogenerated()
    {
        return isAutogenerated;
    }

    public String toExternalForm()
    {
        StringBuffer stringbuffer = new StringBuffer();
        String s;
        StringBuffer stringbuffer1;
        String s1;
        if(getName() == null)
            s = "";
        else
            s = getName();
        stringbuffer1 = stringbuffer.append(s).append(": ");
        if(getValue() == null)
            s1 = "";
        else
            s1 = getValue();
        return stringbuffer1.append(s1).append("\r\n").toString();
    }

    @Override
	public String toString()
    {
        return toExternalForm();
    }

    private boolean isAutogenerated;
}
